# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('visit_date', models.DateField(editable=False, verbose_name='Visit date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('anonymous_hits', models.PositiveIntegerField(default=0, verbose_name='Anonymous user Hits')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('registered_hits', models.PositiveIntegerField(default=0, verbose_name='Registered user hits')),
            ],
            options={
                'ordering': ('-visit_date', '-modified_at'),
                'get_latest_by': 'created_at',
            },
        ),
    ]
