# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-12 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_page_hits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageHits',
            new_name='PageHit',
        ),
    ]
